sudo: required
dist: focal # specify the Ubuntu distribution
services:
  - docker

env: # set up env var to be used in setting image versions
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # this will make sure google cloud does not show any prompts

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d # pull the encrypted service-account.json file from Travis CI and unencrypt it for later authentication to GCP
  - CLOUDSDK_PYTHON=python3.8 # set python version to be 3.8 for successful installation of Google SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null; # download Google SDK and install it locally
  - source $HOME/google-cloud-sdk/path.bash.inc # apply the additional configuration
  - gcloud components update kubectl # make GCP CLI install kubectl command
  - gcloud auth activate-service-account --key-file service-account.json # activate a service account and provide the credential
  - gcloud config set project multi-k8s-409601 # switch to the current GCP project
  - gcloud config set compute/zone us-central1-c # switch to the correct compute zone
  - gcloud container clusters get-credentials multi-cluster # specify the container to issue the command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # login to docker
  - docker build -t howardtian/react-test -f ./client/Dockerfile.dev ./client # build the local test

script:
  - docker run -e CI=true howardtian/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
