apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: htiian/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGUSER
              value: postgres # Not ideal to use the default name, just for a demo purpose
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres # Not ideal to use the default name, just for a demo purpose
            - name: POSTGRES_PASSWORD
              valueFrom: # This is the place where we wire up the secret environment variable
                secretKeyRef:
                  name: pgpassword # This is the name you specified when creating the secret using kubectl CLI
                  key: PGPASSWORD # Find the value associated with this key
